PR from develop to master
YuKopilets/mjc-rest pull request #3
Opened 2020-10-30 21:02 UTC by YuKopilets

Rest api basics task (module2):
https://github.com/mjc-school/MJC-School/blob/master/modules/module%20%232.%20REST%20API%20Basics/rest_api_basics_task.md

2020-11-01 15:27 UTC, maximelyashevich requested changes
Please review my suggestions.

Regards,
Maks

2020-11-01 22:35 UTC, maximelyashevich requested changes
Please review my recommendations. Apart from that, check H2 database schema and verify that all persistence tests are working.

Do not forget that service projects should be covered not less than 80% tests. 

Regards,
Maks

2020-11-01 22:35 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +    private GiftCertificateService giftCertificateService;
I have a proposal: what if apply test configuration like that?

```Java
    private GiftCertificateService giftCertificateService;

    @Mock
    private GiftCertificateDao giftCertificateDao;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.initMocks(this);

        giftCertificateService = spy(
                new GiftCertificateServiceImpl(giftCertificateDao)
        );
    }

    @AfterEach
    void tearDown() {
        giftCertificateDao = null;
        giftCertificateService = null;
    }
```

2020-11-01 22:35 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +@ActiveProfiles("test")
Do we really need id?

2020-11-01 22:35 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +    void addGiftCertificateTest() {
Can you parameterize this method?

Please see `GiftCertificateDaoImplTest` for more details.

2020-11-01 22:35 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +        Mockito.verify(giftCertificateDao).update(giftCertificate.get());
Do not ignore NPE warning for `giftCertificate.get()`.

Please see `GiftCertificateDaoImplTest ` for more details.

2020-11-01 22:35 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/TagServiceImplTest.java
> +class TagServiceImplTest {
Please check recommendations from `GiftCertificateServiceImplTest` and try to apply them for `TagServiceImplTest`.

2020-11-01 22:35 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +    public GiftCertificate updateGiftCertificate(@RequestBody GiftCertificate giftCertificate) {
Does it make sense to use `/certificates/{id}` endpoint?

2020-11-03 00:12 UTC, maximelyashevich requested changes

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/persistence/src/test/java/com/epam/esm/dao/impl/GiftCertificateDaoImplTest.java
> +    }
Please consider `DataProviderUtils` class which can generate the required data.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/persistence/src/test/java/com/epam/esm/dao/impl/TagDaoImplTest.java
> +    }
Please consider `DataProviderUtils` class which can generate the required data.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/GiftCertificateService.java
> +    void addGiftCertificateTags(GiftCertificate giftCertificate);
Please check method name and make it more clear.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        }
```suggestion
        if (id <= 0) {
            throw new InvalidRequestedIdServiceException(id + " does not fit the allowed gap. Expected gap: 0 > id");
        }
         
        Optional<GiftCertificate> giftCertificateById = giftCertificateDao.findById(id);
        return giftCertificateById.orElseThrow(() ->
                    new GiftCertificateNotFoundServiceException("GiftCertificate with id=" + id + " not found")
            );
```

Please consider validation method to check id.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            }
Try to optimize the number of conditional statements.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +            throw new InvalidRequestedIdServiceException(id + " does not fit the allowed gap. Expected gap: 0 > id");
Please consider validation method to check id - the idea is not to have code duplication.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/TagServiceImpl.java
> +public class TagServiceImpl implements TagService {
Please check my recommendations for `GiftSertificateServiceImpl` class.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +            throw new GiftCertificateNotFoundResponseStatusException(e);
Please check if it is a good practice to use log + throw.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/controller/TagController.java
> +public class TagController {
Please check my recommendations for `GiftCertificateController` class.

2020-11-03 00:12 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/exception/GiftCertificateNotFoundResponseStatusException.java
> +public class GiftCertificateNotFoundResponseStatusException extends ResponseStatusException {
What's about `ExceptionHandler` class?

Please weigh up all pros and cons to use the current approach.

2020-11-03 09:48 UTC, YuKopilets commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/GiftCertificateService.java
> +    void addGiftCertificateTags(GiftCertificate giftCertificate);
Can you place me any example how better name them?

2020-11-03 10:25 UTC, MaksimShakavin requested changes

2020-11-03 10:25 UTC, MaksimShakavin commented on GiftCertificatesSystem/persistence/src/test/java/com/epam/esm/dao/impl/GiftCertificateDaoImplTest.java
> +    void findAllGiftCertificatesNegativeTest() {
I like using "should" in tests naming. It makes test more like documentation of the class, and more tdd like. Also you may not rename the test method when you rename the origina method. I.e shouldReturnEmptyWhenNoCertificate, shouldDeleteCertificate, shouldReturnAllCertificated

2020-11-03 10:25 UTC, MaksimShakavin commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/exception/ServiceException.java
> +public class ServiceException extends Exception {
Why not runtimeException? holy war topic

2020-11-03 10:25 UTC, MaksimShakavin commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +    public GiftCertificateServiceImpl(GiftCertificateDao giftCertificateDao) {
can we use lombok here as well?

2020-11-03 10:25 UTC, MaksimShakavin commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/controller/GiftCertificateController.java
> +        } catch (InvalidRequestedIdServiceException e) {
I would better catch one ServiceException and provide an appropriate messages in it's descendants

2020-11-03 12:17 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/GiftCertificateService.java
> +    void addGiftCertificateTags(GiftCertificate giftCertificate);
For example, `addTagsToGiftCerificate()` or `assignTagsToGiftCerificate()`.

2020-11-04 13:03 UTC, YuKopilets commented on GiftCertificatesSystem/persistence/src/main/resources/datasource.properties
> +dataSource.password=root
How can i do it better?

2020-11-04 13:05 UTC, YuKopilets commented on GiftCertificatesSystem/persistence/src/main/java/com/epam/esm/dao/impl/TagDaoImpl.java
> +        } catch (EmptyResultDataAccessException e) {
RowMapper doesn't return null if db hasn't got a record with actual id. It generate EmptyResultDataAccessException

2020-11-04 23:04 UTC, maximelyashevich requested changes
A few minor changes are required.

2020-11-04 23:04 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +        if (giftCertificateOptional.isPresent()) {
You can also use `Optional.ifPresent()` method.

2020-11-04 23:04 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/error/ControllerExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
Can we consider here `Exception` class?

2020-11-05 07:56 UTC, YuKopilets commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/error/ControllerExceptionHandler.java
> +    @ExceptionHandler(RuntimeException.class)
We discussed that only RuntimeExceptions are used in the spring

2020-11-05 07:59 UTC, YuKopilets commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        }
You said me that we can add else block for write more readable code

2020-11-05 08:03 UTC, YuKopilets commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/GiftCertificateServiceImpl.java
> +        }
You said me that we can add else block for write more readable code

2020-11-05 13:03 UTC, maximelyashevich approved these changes

2020-11-05 18:34 UTC, merged