Module 3 pull request [Rest api advanced]
YuKopilets/mjc-rest pull request #4
Opened 2020-11-14 11:44 UTC by YuKopilets

2020-11-16 00:08 UTC, maximelyashevich requested changes

2020-11-16 00:08 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/main/java/com/epam/esm/service/impl/OrderServiceImpl.java
> +        if (!(length >= 4 && length <= 50)) {
Can you explain why we should use this values?

2020-11-16 00:08 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
> +import java.util.*;
**TBD:** Replace it with single import statements.

2020-11-16 00:08 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/dto/GiftCertificatePatchDto.java
> +    @Pattern(regexp = "^[A-Za-z0-9]+(\\s[A-Za-z0-9]+)*$")
**TBD:** Does it make sense to simplify this regexp?

2020-11-16 00:08 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/resources/application.properties
> +#logging.level.root=debug
Do we need this logging config?

2020-11-16 07:11 UTC, YuKopilets commented on GiftCertificatesSystem/persistence/src/main/java/com/epam/esm/dao/impl/GiftCertificateDaoImpl.java
> +                .setParameter("id", giftCertificate.getId())
Value of id substituted in codition part of query, not in SET.

2020-11-18 23:13 UTC, maximelyashevich requested changes
Hi @YuKopilets,

Minor changes are required. And I couldn't find where you used JPA features to get audit data.

Regards,
Maks

2020-11-18 23:13 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/dto/GiftCertificatePatchDto.java
> +    private Set<Tag> tags;
Can we modify tags?

2020-11-18 23:13 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/dto/GiftCertificatePostDto.java
> +    Set<Tag> tags;
Does it make sense to consider unmodifiable collection?

2020-11-23 17:42 UTC, maximelyashevich requested changes
Reviewed from my side, minor changes are required.

Regards,
Maks

2020-11-23 17:42 UTC, maximelyashevich commented on GiftCertificatesSystem/service/src/test/java/com/epam/esm/service/impl/GiftCertificateServiceImplTest.java
>                  .build();
What's about `buildGiftCertificate()` method?

2020-11-23 18:00 UTC, YuKopilets commented on GiftCertificatesSystem/persistence/src/main/java/com/epam/esm/entity/validator/DaysDurationValidator.java
> +        return duration.toDays() > 1;
There is javadoc above class, where is typed about positive number of days. I read practice that we dont need write doc for overided method

2020-11-23 18:08 UTC, maximelyashevich commented on GiftCertificatesSystem/persistence/src/main/java/com/epam/esm/entity/validator/DaysDurationValidator.java
> +        return duration.toDays() > 1;
I thought that positive numberscould be defined by `x > 0`.. But whatever's best for you.

2020-11-23 18:57 UTC, maximelyashevich approved these changes
Reviewed from my side, great job.

Regards,
Maks

2020-11-23 20:49 UTC, merged