PR. MJC-School module 4 (Authentication and Spring Security)
YuKopilets/mjc-rest pull request #5
Opened 2020-12-07 15:29 UTC by YuKopilets

task link: https://github.com/mjc-school/MJC-School/blob/master/modules/module%20%234.%20Authentication%20%26%20Spring%20Security/authentication_and_spring_security_task.md

2020-12-08 23:39 UTC, maximelyashevich requested changes

2020-12-08 23:39 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/com/epam/esm/controller/UserController.java
> +    @PreAuthorize("hasPermission(#id, 'userId', 'hasPermissionToGetUser') or hasRole('ADMIN')")
Just take a look at `hasPermission(hasPermissionToGetUser)`. Can you please simplify permission name?

2020-12-08 23:39 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/db/migration/OrderCostReviewer.java
> +    public OrderCostReviewer(OrderRepository orderRepository) {
Why did you use `public` modifier for constructor?

2020-12-08 23:39 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/db/migration/OrderCostReviewer.java
> +                    "Instance is already created!");
```suggestion
                    "Instance was already created!");
```

2020-12-08 23:39 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/db/migration/OrderCostReviewer.java
> +public class OrderCostReviewer {
To be discussed.

2020-12-08 23:39 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/java/db/migration/V5__Encode_passwords.java
> +                    }
Does it make sense to consider one more method?

2020-12-08 23:39 UTC, maximelyashevich commented on GiftCertificatesSystem/web/src/main/resources/templates/login.html
> +                    <div class="hamburger">
Just one question: why hamburger?

2020-12-09 06:46 UTC, YuKopilets commented on GiftCertificatesSystem/web/src/main/resources/templates/login.html
> +                    <div class="hamburger">
Because it looks like hamberger. Css hamburger is a popular name.  2 440 000 google results per 0.72 seconds.

2020-12-09 06:51 UTC, YuKopilets commented on GiftCertificatesSystem/security/src/main/java/com/epam/esm/service/UserAuthenticationAttributeConstant.java
> +public final class UserAuthenticationAttributeConstant {
We use these constants in this package

2020-12-09 23:35 UTC, maximelyashevich requested changes

2020-12-09 23:35 UTC, maximelyashevich commented on GiftCertificatesSystem/security/src/main/java/com/epam/esm/service/OAuth2Authentication.java
> +public enum OAuth2Authentication {
To be discussed. Before that, please check out template method pattern.

2020-12-10 18:44 UTC, maximelyashevich approved these changes

2020-12-11 06:10 UTC, merged